#ifndef SYMBOL_H
#define SYMBOL_H

#include <string>

#define SYMBOLSIZE = 47; 

enum Symbol {ID, NUM, PLUS, MINUS, PERIOD,
	     COMMA, SEMICOLON, LEFTSQUARE, RIGHTSQUARE, AMPERSAND,   
	     VERTICAL, TILDE, LESSTHAN, EQUAL, GREATERTHAN,
	     STAR, SLASH, BACKSLASH, LEFTBRACKET, RIGHTBRACKET,
	     ASSIGNMENT, SQUARE, ARROW, COMMENT, BEGIN,
	     END, CONST, ARRAY, INTEGER, BOOLEAN,
	     PROC, SKIP, READ, WRITE, CALL,
	     IF, FI, DO, OD, FALSE,
	     TRUE, NONAME, BADNAME, BADNUM, ENDOFFILE,
	     NEWLINE, BADCHAR
};

#endif
