#include <string>

enum Symbol {ID, NUM, PLUS, MINUS, PERIOD,
  COMMA, SEMICOLON, LEFTSQUARE, RIGHTSQUARE, AMPERSAND,
VERTICAL, TILDE, LESSTHAN, EQUAL, GREATERTHAN,
STAR, SLASH, BACKSLASH, LEFTBRACKET, RIGHTBRACKET,
ASSIGNMENT, SQUARE, ARROW, COMMENT, NONAME,
BADNAME, BADNUM, ENDOFFILE, NEWLINE, BADCHAR};


//251 - 256
//256 - 260
//261 - 265
//266 - 270
//271 - 275
//276 - 280
